# Build BASE
FROM node:22-alpine AS base

WORKDIR /app
COPY package.json yarn.lock ./
RUN apk add --no-cache libc6-compat \
    && yarn --frozen-lockfile \
    && yarn cache clean

# Build stage
FROM node:22-alpine AS build

WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY . .
RUN yarn build

# Production stage
FROM node:22-alpine AS production

WORKDIR /app

# Copy built application
COPY --from=build /app/public ./public
COPY --from=build /app/next.config.mjs ./
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
